In [1]:
import torch
mask = torch.tensor([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0], dtype=torch.long)
print(mask)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0])


In [2]:
def reverse_x_idx(mask,max_len):
    idx_actual_len = torch.sum(mask, dim=0)
    reverse_idx = torch.cat([torch.arange(0,idx_actual_len).flip(0),torch.arange(idx_actual_len,max_len)],dim=0)
    return reverse_idx

reverse_idx = reverse_x_idx(mask, mask.size(0))
print(reverse_idx)

tensor([16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26])


In [11]:
def reverse_x(x, rev_idx):
    return x.index_select(0, rev_idx.to(x.device))

x = torch.randn(mask.size(0), 3)
print(x)
rev_x = reverse_x(x, reverse_idx)
print('----------------------------------')
print(rev_x)

tensor([[ 0.6629,  0.6738,  1.0984],
        [-0.8316, -1.2894, -1.3088],
        [ 1.9054, -0.2226, -0.0591],
        [ 0.6209, -0.4450,  0.8549],
        [-0.0870, -0.5653, -0.2183],
        [ 0.7089,  0.7173,  0.5894],
        [-1.0869,  0.6915, -0.1289],
        [-1.3462, -0.0712,  0.3928],
        [ 1.6022,  0.7539, -0.7201],
        [ 1.2009, -0.5068,  0.3092],
        [-1.2862,  1.3798,  0.7447],
        [-0.7266, -0.0875, -0.6420],
        [-1.3129, -0.5802, -0.0506],
        [ 0.0486, -2.7370,  0.2761],
        [-0.0428, -0.4391,  0.3238],
        [-1.3580, -0.0310, -0.5677],
        [-1.0666, -0.3272, -1.1164],
        [ 0.5284, -2.9404, -0.3438],
        [ 0.5718,  0.8546, -1.9102],
        [ 0.1571, -1.1835,  0.1889],
        [ 0.2153,  0.6608,  0.8737],
        [ 0.3630,  0.6763,  1.9349],
        [ 0.3691, -0.9020, -1.3585],
        [-0.1819,  0.0612, -0.2521],
        [ 0.4604, -1.1519,  0.5941],
        [-0.3449,  1.7198, -1.2018],
        [ 0.5349,  2.1818, -0.7377]])


In [12]:
def create_mask(x):
    mask = torch.ones(x.size(0)).to(x.device)
    mask[x == 0] = 0
    return mask.to(torch.long)

x = [3,323,424,3423,4244,12323,4244,45,24,2112,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
x = torch.tensor(x,dtype=torch.long)
mask = create_mask(x)
print(mask)


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0])
